<!-- START of: finna - content/Additions/recover-post.phtml -->
<?php if (!$this->translationEmpty('library_card_recovery_help_html')): ?>
    <p><?=$this->translate('library_card_recovery_help_html');?></p>
<?php // password_recovery_info is unescaped as it is unofficial translation key but used in many sites. ?>
<?php else if (!$this->translationEmpty('password_recovery_info')): ?>
    <p><?=$this->translate('password_recovery_info') ?></p>
<?php endif; ?>
<!-- END of: finna - content/Additions/recover-post.phtml -->
